CREATE TABLE IF NOT EXISTS new_admission(
    ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL,
    PHONE VARCHAR(50) NOT NULL,
    DOB VARCHAR(50) NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    SENIOR_QUAL VARCHAR(50) NOT NULL,
    HIGHER_QUAL VARCHAR(50) NOT NULL,
    COURSE VARCHAR(50) NOT NULL,
    ADRESS_1 VARCHAR(50) NOT NULL,
    ADRESS_2 VARCHAR(50) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    CITY VARCHAR(50) NOT NULL,
    REGION VARCHAR(50) NOT NULL,
    PINCODE VARCHAR(50) NOT NULL
);