CREATE TABLE IF NOT EXISTS new_staff (
  ID int PRIMARY KEY AUTO_INCREMENT,
  NAME varchar(50) NOT NULL,
  EMAIL varchar(50) NOT NULL,
  PASSWORD varchar(50) NOT NULL,
  PHONE varchar(50) NOT NULL,
  DOB varchar(50) NOT NULL,
  GENDER varchar(10) NOT NULL,
  SENIOR_QUAL varchar(50) NOT NULL,
  HIGHER_QUAL varchar(50) NOT NULL,
  SUBJECTS json NOT NULL,
  ADRESS_1 varchar(50) NOT NULL,
  ADRESS_2 varchar(50) NOT NULL,
  COUNTRY varchar(50) NOT NULL,
  CITY varchar(50) NOT NULL,
  REGION varchar(50) NOT NULL,
  PINCODE varchar(50) NOT NULL
);